from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


METRIC_KEYS = [
    "chunk_count",
    "issue_count",
    "rule_candidate_count",
    "table_like_chunks",
    "table_cell_row_count",
    "quality_score",
]


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def delta(new: int | float, old: int | float) -> dict[str, float]:
    change = new - old
    percent = (change / old * 100.0) if old else 0.0
    return {"old": old, "new": new, "delta": change, "delta_percent": round(percent, 2)}


def compare_counts(before: dict[str, Any], after: dict[str, Any], key: str) -> dict[str, dict[str, Any]]:
    before_counts = before.get(key, {}) or {}
    after_counts = after.get(key, {}) or {}
    labels = sorted(set(before_counts) | set(after_counts))
    return {label: delta(after_counts.get(label, 0), before_counts.get(label, 0)) for label in labels}


def compare(before: dict[str, Any], after: dict[str, Any]) -> dict[str, Any]:
    result: dict[str, Any] = {
        "before_document_id": before.get("document_id"),
        "after_document_id": after.get("document_id"),
        "metrics": {},
        "chunk_length": {
            "median": delta(after["chunk_length"]["median"], before["chunk_length"]["median"]),
            "max": delta(after["chunk_length"]["max"], before["chunk_length"]["max"]),
            "over_2300": delta(after["chunk_length"]["over_2300"], before["chunk_length"]["over_2300"]),
        },
        "chunk_types": compare_counts(before, after, "chunk_types"),
        "issue_types": compare_counts(before, after, "issue_types"),
        "rule_categories": compare_counts(before, after, "rule_categories"),
        "table_metrics": compare_counts(before, after, "table_metrics"),
        "metadata_coverage": compare_counts(before, after, "metadata_coverage"),
        "quality": {
            "before_passed": before.get("quality_passed"),
            "after_passed": after.get("quality_passed"),
            "before_score": before.get("quality_score"),
            "after_score": after.get("quality_score"),
        },
    }
    for key in METRIC_KEYS:
        result["metrics"][key] = delta(numeric_metric(after, key), numeric_metric(before, key))
    return result


def numeric_metric(payload: dict[str, Any], key: str) -> int | float:
    value = payload.get(key, 0)
    if isinstance(value, bool) or value is None:
        return 0
    if isinstance(value, (int, float)):
        return value
    return 0


def markdown_report(result: dict[str, Any]) -> str:
    lines = [
        f"# Regulation Run Comparison",
        "",
        f"- Before: `{result['before_document_id']}`",
        f"- After: `{result['after_document_id']}`",
        "",
        "## Core Metrics",
        "",
    ]
    for key, value in result["metrics"].items():
        lines.append(
            f"- {key}: {value['old']:,} -> {value['new']:,} ({value['delta']:+,}, {value['delta_percent']}%)"
        )
    lines.extend(["", "## Chunk Length", ""])
    for key, value in result["chunk_length"].items():
        lines.append(
            f"- {key}: {value['old']:,} -> {value['new']:,} ({value['delta']:+,}, {value['delta_percent']}%)"
        )
    lines.extend(["", "## Chunk Types", ""])
    for key, value in result["chunk_types"].items():
        lines.append(
            f"- {key}: {value['old']:,} -> {value['new']:,} ({value['delta']:+,}, {value['delta_percent']}%)"
        )
    lines.extend(["", "## Table Metrics", ""])
    for key, value in result["table_metrics"].items():
        lines.append(
            f"- {key}: {value['old']:,} -> {value['new']:,} ({value['delta']:+,}, {value['delta_percent']}%)"
        )
    lines.extend(["", "## Metadata Coverage", ""])
    for key, value in result["metadata_coverage"].items():
        lines.append(
            f"- {key}: {value['old']:,} -> {value['new']:,} ({value['delta']:+,}, {value['delta_percent']}%)"
        )
    lines.extend(["", "## Issue Types", ""])
    if result["issue_types"]:
        for key, value in result["issue_types"].items():
            lines.append(
                f"- {key}: {value['old']:,} -> {value['new']:,} ({value['delta']:+,}, {value['delta_percent']}%)"
            )
    else:
        lines.append("- No issues in either run")
    lines.extend(["", "## Interpretation", ""])
    issue_delta = result["metrics"]["issue_count"]
    duplicate_note = "Chunk IDs are expected to be unique in the after run when generated by the current chunker."
    lines.append(f"- Validation issues changed by {issue_delta['delta']:+,}.")
    if result["quality"]["after_score"] is not None:
        lines.append(f"- Quality gate after run: {result['quality']['after_passed']} / score {result['quality']['after_score']}.")
    lines.append(f"- {duplicate_note}")
    lines.append("- Review samples, not only aggregate counts, before promoting learned rules globally.")
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare two RegRAG Prep analysis runs.")
    parser.add_argument("--before", required=True)
    parser.add_argument("--after", required=True)
    parser.add_argument("--out-prefix", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    before = load(Path(args.before))
    after = load(Path(args.after))
    result = compare(before, after)
    prefix = Path(args.out_prefix)
    prefix.parent.mkdir(parents=True, exist_ok=True)
    json_path = prefix.with_suffix(".json")
    md_path = prefix.with_suffix(".md")
    json_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    md_path.write_text(markdown_report(result), encoding="utf-8")
    print(json.dumps({"json": str(json_path), "markdown": str(md_path)}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
